---
services: [docker]
language: python
dist: focal
git: {lfs_skip_smudge: true}
env:
  global:
    - |
      __NAME__="postgresql" \
      RELEASE_DEBUG="" \
      COPS_URL="https://github.com/corpusops/corpusops.bootstrap" \
      COPS_ROOT="$HOME/corpusops/corpusops.bootstrap" \
      funcs="$COPS_ROOT/bin/cops_shell_common" \
      silent="$funcs output_in_error silent_vv" \
      apply_role="sudo -E $silent $COPS_ROOT/bin/cops_apply_role -vvvvv" \
      release="$COPS_ROOT/hacking/docker_release" \
      silent_rm="$silent rm -rf"
  matrix:
    - IMAGES="corpusops/postgresql:9.6"
    - IMAGES="corpusops/postgresql:9.5"
    - IMAGES="corpusops/postgresql:9.4"
    - IMAGES="corpusops/postgresql:9.3"
    - IMAGES="corpusops/postgresql:9.2"
    - IMAGES="corpusops/postgresql:10"
    - IMAGES="corpusops/postgresql:11"
    - IMAGES="corpusops/postgresql:12"
#   - IMAGES="corpusops/postgis:9.6"
#   - IMAGES="corpusops/postgis:9.5"
#   - IMAGES="corpusops/postgis:9.4"
#   - IMAGES="corpusops/postgis:9.3"
#   - IMAGES="corpusops/postgis:9.2"
#   - IMAGES="corpusops/postgis:10"
language: python
python: "2.7"
before_install:
- sudo apt-get update -qq
- sudo service docker stop
- .ansible/scripts/download_corpusops.sh
- $silent .ansible/scripts/setup_corpusops.sh
- >
  sudo bash -exc "python -c
  \"d='/etc/docker/daemon.json';
  import json;
  c = json.load(open(d));
  c['experimental'] = True;
  print(c);open(d, 'w').write(json.dumps(c))
  \"
  && systemctl restart docker"
- echo "$DOCKER_PASSWORD" | docker login --password-stdin --username="$DOCKER_RELEASER"
script:
  - set -e;for i in $IMAGES;do $silent .ansible/scripts/build_docker_images.sh --images $i;done
after_success:
  - docker images
  - |
    set -e;
    for i in $IMAGES;do
     if [ "x$RELEASE_DEBUG" = "x" ];then
       DEBUG=1 $funcs vv $release $i
     else
       $silent $release $i
     fi
    done
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/corpusops
