---
# install custom config files
- include_role: {name: corpusops.roles/configs, private: true}
  vars:
    cops_configs_templates: "{{cops_postgresql_vars.configs}}"
    cops_configs_notify: "{{cops_postgresql_vars.rhandlers}}"
  tags: [postgresql, configs, postgresql_configs]
