---
# Configure things before systemd launches
- name: maybe enable some services
  changed_when: false
  cops_service:
    enabled: true
    name: postgresql
- when: "cops_postgresql_do_reconfigure_db|default(true)"
  changed_when: false
  name: "reconfigure DB"
  shell: |-
    set -ex
    cd "{{cops_postgresql_vars.provision_dir}}"
    export NONINTERACTIVE=1
    v=$(psql --version |awk '{print $3}'|sed -re "s/\..*//g")
    export PATH=/usr/lib/postgresql/$v/bin:$PATH
    cn="/etc/postgresql/$v/main"
    c="/var/lib/postgresql/$v/main"
    if [ ! -e "$c" ];then
      mkdir -p "$c"
      chown postgres:postgres "$c"
      su postgres -c \
       "export PATH=$PATH; \
        initdb -D $c --locale='{{corpusops_services_db_postgresql_pg_conf_locale}}'"
      if [ ! -e "$cn" ];then
        mkdir -p "$cn"
        cp -fv "$c"/*conf "$cn"
      fi
    fi
    chown -Rf postgres:postgres "$c" /var/log/postgresql
