---
- name: update & install prerequisites
  package:
    cache_valid_time: '{{60*60}}'
    update_cache: yes
    name: '{{item}}'
    state: present
  when: "cops_postgresql_s_prerequisites_pkgs and (
          ansible_os_family.lower() in ['debian'] and
          cops_postgresql_vars.deb_packages is not none and
          cops_postgresql_vars.deb_packages|length > 0)"
  with_items: "{{cops_postgresql_vars.deb_packages}}"
  tags: [cops_postgresql_s_prerequisites_pkgs]
- name: update & install prerequisites
  package:
    update_cache: yes
    enablerepo: epel,epel-testing
    name: '{{item}}'
    state: present
  when: "cops_postgresql_s_prerequisites_pkgs and (
          ansible_os_family.lower() in ['redhat'] and
          cops_postgresql_vars.rh_packages is not none and
          cops_postgresql_vars.rh_packages|length > 0)"
  with_items: "{{cops_postgresql_vars.rh_packages}}"
  tags: [cops_postgresql_s_prerequisites_pkgs]
