---
- include_role: {name: corpusops.roles/configs, private: true}
  vars:
    cops_configs_templates: "{{cops_postgresql_vars.ep_configs}}"
    cops_configs_notify: "{{cops_postgresql_vars.rhandlers}}"
  tags: [cops_postgresql_s_entry_point]
  when: [cops_postgresql_s_entry_point]
