---
- when: ["cops_postgresql_s_workers_service and corpusops_vars.has_services_manager"]
  tags: ["cops_postgresql_s_workers_service"]
  block:
  # activate the main app service
  - service:
      state: "{{cops_postgresql_vars.activated | ternary('started', 'stopped')}}"
      enabled: "{{cops_postgresql_vars.activated | ternary(True, False)}}"
      name: "{{item}}"
    with_items: "{{cops_postgresql_vars.services}}"
  # this will fail on non systemd hosts on purpose !
  # if we have activated the reconfigure units (docker mode essentially)
  - systemd:
      enabled: "{{cops_postgresql_vars.activated | ternary(True, False)}}"
      daemon_reload: yes
      name: "{{item}}"
    with_items: "{{cops_postgresql_vars.reconfigure_services}}"
  # force a reload/restart here
  - shell: echo "force service reload/restart"
    notify: "{{cops_postgresql_vars.rhandlers}}"
  - meta: flush_handlers

# check pg is running
- tags: [cops_postgresql_s_workers_checks]
  when: [cops_postgresql_s_workers_checks]
  block:
  - shell: |
      echo "select 1"| psql -v ON_ERROR_STOP=1 -t -A -F",":
    when: "(corpusops_vars.has_services_manager and
            cops_postgresql_vars.activated)"
    register: cops_postgresql_check
    until: "'1' == cops_postgresql_check.stdout"
    retries: 10
    delay: 1
    become: true
    become_user: postgres
