---
# activate the main app service
- cops_service:
    state: "{{cops_postgresql_vars.activated | ternary('started', 'stopped')}}"
    enabled: "{{cops_postgresql_vars.activated | ternary(True, False)}}"
    name: "{{item}}"
  loop: "{{cops_postgresql_vars.services}}"
# force a reload/restart here
- shell: echo "force service reload/restart"
  notify: "{{cops_postgresql_vars.rhandlers}}"
- meta: flush_handlers
