---
- block:
  - set_fact:
      cacheable: false
      only_steps: "{{only_steps|default(False)}}"
  - set_fact:
      cacheable: false
      cops_postgresql_lifecycle_app_push_code: "{{cops_postgresql_lifecycle_app|default(cops_postgresql_lifecycle_app_push_code|default(not only_steps))}}"
  - set_fact:
      cacheable: false
      cops_postgresql_s_managecontent_privs:      "{{cops_postgresql_s_managecontent|default(cops_postgresql_s_managecontent_privs     |default(not only_steps))}}"
      cops_postgresql_s_managecontent_roles:      "{{cops_postgresql_s_managecontent|default(cops_postgresql_s_managecontent_roles     |default(not only_steps))}}"
      cops_postgresql_s_managecontent_databases:  "{{cops_postgresql_s_managecontent|default(cops_postgresql_s_managecontent_databases |default(not only_steps))}}"
      cops_postgresql_s_setup_sysctls:            "{{cops_postgresql_s_setup|default(cops_postgresql_s_setup_sysctls           |default(not only_steps))}}"
      cops_postgresql_s_setup_server_postgresql:  "{{cops_postgresql_s_setup|default(cops_postgresql_s_setup_server_postgresql |default(not only_steps))}}"
      cops_postgresql_s_setup_server_postgis:     "{{cops_postgresql_s_setup|default(cops_postgresql_s_setup_server_postgis    |default(not only_steps))}}"
      cops_postgresql_s_setup_server:             "{{cops_postgresql_s_setup|default(cops_postgresql_s_setup_server            |default(not only_steps))}}"
      cops_postgresql_s_setup_configs:            "{{cops_postgresql_s_setup|default(cops_postgresql_s_setup_configs           |default(not only_steps))}}"
  - set_fact:
      cacheable: false
      cops_postgresql_s_users:          "{{cops_postgresql_s_users         |default(not only_steps)}}"
      cops_postgresql_s_layout:         "{{cops_postgresql_s_layout        |default(not only_steps)}}"
      cops_postgresql_s_first_fixperms: "{{cops_postgresql_s_first_fixperms|default(not only_steps)}}"
      cops_postgresql_s_prerequisites:  "{{cops_postgresql_s_prerequisites |default(not only_steps)}}"
      cops_postgresql_s_workers:        "{{cops_postgresql_s_workers       |default(not only_steps)}}"
      cops_postgresql_s_entry_point:    "{{cops_postgresql_s_entry_point   |default(not only_steps)}}"
      cops_postgresql_s_end_fixperms:   "{{cops_postgresql_s_end_fixperms  |default(not only_steps)}}"
      cops_postgresql_s_managecontent: "{{(
          cops_postgresql_s_managecontent_privs or
          cops_postgresql_s_managecontent_roles or
          cops_postgresql_s_managecontent_databases)}}"
      cops_postgresql_s_setup: "{{(
          cops_postgresql_s_setup_sysctls or
          cops_postgresql_s_setup_server_postgresql or
          cops_postgresql_s_setup_server_postgis or
          cops_postgresql_s_setup_server or
          cops_postgresql_s_setup_configs)}}"
  - set_fact:
      cacheable: false
      cops_postgresql_lifecycle_app_level_1_steps: "{{(
          cops_postgresql_s_users or
          cops_postgresql_s_layout or
          cops_postgresql_s_first_fixperms or
          cops_postgresql_s_prerequisites or
          cops_postgresql_s_setup or
          cops_postgresql_s_workers or
          cops_postgresql_s_entry_point or
          cops_postgresql_s_managecontent or
          cops_postgresql_s_end_fixperms)}}"
  - set_fact:
      cacheable: false
      cops_postgresql_lifecycle_app_setup: "{{(cops_postgresql_lifecycle_app_setup|default(
                                                (cops_postgresql_lifecycle_app|default(False)) or (
                                                  cops_postgresql_lifecycle_app_level_1_steps)))}}"
  - set_fact:
      cacheable: false
      cops_postgresql_lifecycle_app: "{{(
        cops_postgresql_lifecycle_app_push_code or
        cops_postgresql_lifecycle_app_setup)}}"
  - set_fact:
      cacheable: false
      cops_postgresql_lifecycle_app_lc_1_steps: "{{(
          cops_postgresql_lifecycle_app)}}"
  - set_fact:
      cacheable: false
      cops_postgresql_s_vars: "{{cops_postgresql_s_vars|default(cops_postgresql_lifecycle_app_lc_1_steps)}}"


