---
- include_jinja_vars:
    content: |-
      {% set r = {} %}
      {% set _ = r.update({'only_steps': only_steps|default(False)}) %}
      {% set only_steps = r['only_steps'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_users_user':      cops_postgresql_s_users_user    |default(cops_postgresql_s_users|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_users_user = r['cops_postgresql_s_users_user'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_setup_config':      cops_postgresql_s_setup_config    |default(cops_postgresql_s_setup|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_setup_config = r['cops_postgresql_s_setup_config'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_users_group':      cops_postgresql_s_users_group    |default(cops_postgresql_s_users|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_users_group = r['cops_postgresql_s_users_group'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_manage_content_privs':      cops_postgresql_s_manage_content_privs    |default(cops_postgresql_s_manage_content|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_manage_content_privs = r['cops_postgresql_s_manage_content_privs'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_manage_content_roles':      cops_postgresql_s_manage_content_roles    |default(cops_postgresql_s_manage_content|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_manage_content_roles = r['cops_postgresql_s_manage_content_roles'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_prerequisites_postgresql':  cops_postgresql_s_prerequisites_postgresql|default(cops_postgresql_s_prerequisites|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_prerequisites_postgresql = r['cops_postgresql_s_prerequisites_postgresql'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_prerequisites_pkgs':  cops_postgresql_s_prerequisites_pkgs|default(cops_postgresql_s_prerequisites|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_prerequisites_pkgs = r['cops_postgresql_s_prerequisites_pkgs'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_prerequisites_postgis':  cops_postgresql_s_prerequisites_postgis|default(cops_postgresql_s_prerequisites|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_prerequisites_postgis = r['cops_postgresql_s_prerequisites_postgis'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_manage_content_postgis':  cops_postgresql_s_manage_content_postgis|default(cops_postgresql_s_manage_content|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_manage_content_postgis = r['cops_postgresql_s_manage_content_postgis'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_manage_content_fixencoding':  cops_postgresql_s_manage_content_fixencoding|default(cops_postgresql_s_manage_content|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_manage_content_fixencoding = r['cops_postgresql_s_manage_content_fixencoding'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_manage_content_databases':  cops_postgresql_s_manage_content_databases|default(cops_postgresql_s_manage_content|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_manage_content_databases = r['cops_postgresql_s_manage_content_databases'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_setup_sysctls':            cops_postgresql_s_setup_sysctls          |default(cops_postgresql_s_setup        |default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_setup_sysctls = r['cops_postgresql_s_setup_sysctls'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_setup_server_postgresql':  cops_postgresql_s_setup_server_postgresql|default(cops_postgresql_s_setup_server|default(cops_postgresql_s_setup        |default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps)))))}) %}
      {% set cops_postgresql_s_setup_server_postgresql = r['cops_postgresql_s_setup_server_postgresql'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_setup_server_postgis':     cops_postgresql_s_setup_server_postgis   |default(cops_postgresql_s_setup_server|default(cops_postgresql_s_setup        |default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps)))))}) %}
      {% set cops_postgresql_s_setup_server_postgis = r['cops_postgresql_s_setup_server_postgis'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_setup_server':             (cops_postgresql_s_setup_server_postgresql or cops_postgresql_s_setup_server_postgis)}) %}
      {% set cops_postgresql_s_setup_server = r['cops_postgresql_s_setup_server'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_docker_reconfigure': cops_postgresql_s_docker_reconfigure|default(False)}) %}
      {% set cops_postgresql_s_docker_reconfigure = r['cops_postgresql_s_docker_reconfigure'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_setup_configs':            cops_postgresql_s_setup_configs          |default(cops_postgresql_s_setup        |default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_setup_configs = r['cops_postgresql_s_setup_configs'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_users': cops_postgresql_s_users_user or cops_postgresql_s_users_group}) %}
      {% set cops_postgresql_s_users = r['cops_postgresql_s_users'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_layout':         cops_postgresql_s_layout        |default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps)))}) %}
      {% set cops_postgresql_s_layout = r['cops_postgresql_s_layout'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_fixperms_run': cops_postgresql_s_fixperms_run|default(cops_postgresql_s_first_fixperms|default(not only_steps) or cops_postgresql_s_end_fixperms|default(not only_steps))}) %}
      {% set cops_postgresql_s_fixperms_configs = r['cops_postgresql_s_fixperms_configs'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_fixperms_configs': cops_postgresql_s_fixperms_configs|default(cops_postgresql_s_first_fixperms|default(not only_steps) or cops_postgresql_s_end_fixperms|default(not only_steps))}) %}
      {% set cops_postgresql_s_fixperms_configs = r['cops_postgresql_s_fixperms_configs'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_end_fixperms'  :   (cops_postgresql_s_end_fixperms|default(not only_steps))}) %}
      {% set cops_postgresql_s_end_fixperms = r['cops_postgresql_s_end_fixperms'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_first_fixperms': (cops_postgresql_s_first_fixperms|default(not only_steps))}) %}
      {% set cops_postgresql_s_first_fixperms = r['cops_postgresql_s_first_fixperms'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_prerequisites': (cops_postgresql_s_prerequisites_postgresql or cops_postgresql_s_prerequisites_postgis or cops_postgresql_s_prerequisites_pkgs)}) %}
      {% set cops_postgresql_s_prerequisites = r['cops_postgresql_s_prerequisites'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_healthchecks':        cops_postgresql_s_healthchecks       |default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps)))}) %}
      {% set cops_postgresql_s_healthchecks = r['cops_postgresql_s_healthchecks'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_workers_service': cops_postgresql_s_workers_service|default(cops_postgresql_s_workers|default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))))}) %}
      {% set cops_postgresql_s_workers_service = r['cops_postgresql_s_workers_service'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_workers': cops_postgresql_s_workers_service}) %}
      {% set cops_postgresql_s_workers = r['cops_postgresql_s_workers'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_entry_point':   (cops_postgresql_s_entry_point   |default(cops_postgresql_lifecycle_app_setup|default(cops_postgresql_lifecycle_app|default(not only_steps))) and ansible_virtualization_type in ['docker'])}) %}
      {% set cops_postgresql_s_entry_point = r['cops_postgresql_s_entry_point'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_manage_content': ( cops_postgresql_s_manage_content_privs or cops_postgresql_s_manage_content_roles or cops_postgresql_s_manage_content_databases or cops_postgresql_s_manage_content_fixencoding or cops_postgresql_s_manage_content_postgis)}) %}
      {% set cops_postgresql_s_manage_content = r['cops_postgresql_s_manage_content'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_setup': ( cops_postgresql_s_setup_sysctls or cops_postgresql_s_setup_server_postgresql or cops_postgresql_s_setup_server_postgis or cops_postgresql_s_setup_server or cops_postgresql_s_setup_configs or cops_postgresql_s_docker_reconfigure)}) %}
      {% set cops_postgresql_s_setup = r['cops_postgresql_s_setup'] %}
      #
      {% set _ = r.update({'cops_postgresql_lifecycle_app_level_1_steps': ( cops_postgresql_s_users or cops_postgresql_s_layout or cops_postgresql_s_first_fixperms or cops_postgresql_s_prerequisites or cops_postgresql_s_setup or cops_postgresql_s_workers or cops_postgresql_s_entry_point or cops_postgresql_s_manage_content or cops_postgresql_s_healthchecks or cops_postgresql_s_end_fixperms)}) %}
      {% set cops_postgresql_lifecycle_app_level_1_steps = r['cops_postgresql_lifecycle_app_level_1_steps'] %}
      #
      {% set _ = r.update({'cops_postgresql_lifecycle_app_push_code': cops_postgresql_lifecycle_app_push_code|default(cops_postgresql_lifecycle_app|default(not only_steps))}) %}
      {% set cops_postgresql_lifecycle_app_push_code = r['cops_postgresql_lifecycle_app_push_code'] %}
      #
      {% set _ = r.update({'cops_postgresql_lifecycle_app_setup': (cops_postgresql_lifecycle_app_setup|default( (cops_postgresql_lifecycle_app|default(False)) or ( cops_postgresql_lifecycle_app_level_1_steps)))}) %}
      {% set cops_postgresql_lifecycle_app_setup = r['cops_postgresql_lifecycle_app_setup'] %}
      #
      {% set _ = r.update({'cops_postgresql_lifecycle_app': ( cops_postgresql_lifecycle_app_push_code or cops_postgresql_lifecycle_app_setup)}) %}
      {% set cops_postgresql_lifecycle_app = r['cops_postgresql_lifecycle_app'] %}
      #
      {% set _ = r.update({'cops_postgresql_s_vars': cops_postgresql_s_vars|default(cops_postgresql_lifecycle_app)}) %}
      {% set cops_postgresql_s_vars = r['cops_postgresql_s_vars'] %}
      #
      {{ r | to_json }}
