---
# generate password on remote box if not found
- name: "postgresql secret generation: {{postgresqlsecret}}"
  include_role:
    name: corpusops.roles/get_secret_variable
  vars:
    _cops_get_secret_variable:
      name: "cops_postgresql_{{postgresqlsecret}}"
      path: "/etc/postgresql-{{cops_postgresql_vars.name}}-secrets"
  when: not vars.get('cops_postgresql_{0}'.format(postgresqlsecret), None)
  no_log: "{{not (cops_secret_vars_debug|default(false))}}"
- debug:
    var: "{{'cops_postgresql_{0}'.format(postgresqlsecret)}}"
  register: cops_secret_value
  no_log: "{{not (cops_secret_vars_debug|default(false))}}"
- name: "Update registry with {{postgresqlsecret}}"
  include_jinja_vars:
    content: |
      ---
      {% set d = postgresqlsecret %}
      {% set p = 'cops_postgresql_' %}
      {% set v = p+d %}
      {% set n = p+'vars' %}
      {% set _vars = {} %}
      {% set _ = _vars.update(cops_secret_value) %}
      {{(_vars | copsf_registry(p, namespaced=vars[n]))[0]| to_json }}
  no_log: "{{not (cops_vars_debug|default(false))}}"
