---
- listen: restart_cops_postgresql
  systemd:
    daemon_reload: yes
    state: restarted
    name: "{{item}}"
  with_items: "{{cops_postgresql_vars.services}}"
  when: "(cops_postgresql_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"
- listen: restart_cops_postgresql
  service:
    state: restarted
    name: "{{item}}"
  with_items: "{{cops_postgresql_vars.services}}"
  when: "(cops_postgresql_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr != 'systemd'))"
- listen: reload_cops_postgresql
  systemd:
    daemon_reload: yes
    state: reloaded
    name: "{{item}}"
  with_items: "{{cops_postgresql_vars.services}}"
  when: "(cops_postgresql_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"
- listen: reload_cops_postgresql
  service:
    state: reloaded
    name: "{{item}}"
  with_items: "{{cops_postgresql_vars.services}}"
  when: "(cops_postgresql_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr != 'systemd'))"
